# yaml-language-server: $schema=https://raw.githubusercontent.com/DavidAnson/markdownlint/main/schema/markdownlint-config-schema.json
default: true

MD013: false
MD028: false
MD033: false
MD046: false
